name: 'Get global configuration'
description: 'Get the global configuration and secrets from Azure KeyVault'
inputs:
  environment:
    required: true
    description: Get the configuration for the specified environment
  debug:
    required: false
    type: boolean
    default: false
    description: Flag to debug this action, default is false

runs:
  using: "composite"
  steps:

    - name: Get service metadata from pom.xml
      shell: bash
      run: |
        echo " "
        echo "Configuration for environment: ${{ inputs.environment }} "
        echo " "
        echo "**************************************"
        echo "Getting service metadata from pom.xml "
        echo "**************************************"
        echo " "

        echo "Install XMLStarlet in Ubuntu"
        sudo apt-get install xmlstarlet --fix-missing        
        echo " "

        echo "xmlstarlet --version"
        xmlstarlet --version
        echo " "

        echo "Get info from pom.xml"
        servicename=$( xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:name" pom.xml )
        serviceversion=$( xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:version" pom.xml )
        servicegroup=$( xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:groupId" pom.xml )
        serviceartifact=$( xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:artifactId" pom.xml )
        echo " "

        echo "Create environment variables with pom data"
        echo "service_name=$servicename" >> $GITHUB_ENV
        echo "service_version=$serviceversion" >> $GITHUB_ENV
        echo "service_group=$servicegroup" >> $GITHUB_ENV
        echo "service_artifact=$serviceartifact" >> $GITHUB_ENV
        echo " "

        echo "Service information:"
        echo "  service_name= " $servicename
        echo "  service_version= " $serviceversion          
        echo "  service_group= " $servicegroup
        echo "  service_artifact= " $serviceartifact

    - name: Get configuration files
      uses:  btfacrm/common-devops/packages/get-file@main
      with:
        file: "_global.yml $service_name.yml"

    - name: DEBUG show configuration files
      shell: bash
      run: |
        cat ¨
        cat "$service_name.yml"

    - name: Import variables from _global.yml
      uses: zlatko-ms/envarfiles@main
      with:
        paths: _global.yml



