name: 'Get configuration file'
description: 'Get the configuration file for the service defined in pom.xml'
inputs:
  file: 
    required: true
    description: File to download

outputs:
  configuration-data:
    description: "The contents of the configuration file"
    value: ${{ steps.configuration.outputs.configuration-data }}
runs:
  using: "composite"
  steps:
    
    - id: configuration
      name: Get configuration for the service 
      shell: bash
      run: |

        echo " "
        echo "*********************************************"
        echo "Get configuration file"
        echo "*********************************************"
        echo " "
        echo "github_automationbot_token: $github_automationbot_token"
        echo "inputs.file: ${{ inputs.file }}"
        listFiles="${{ inputs.file }}"
        for readFile in $listFiles
        do
          echo "  "
          echo "  Getting the file: $readFile"
          urlconfigurationfile="https://raw.githubusercontent.com/${{ github.repository_owner }}/$CONFIGURATIONS_REPOSITORY/main/$readFile"
          echo "  URL of file: $urlconfigurationfile"
          configurationdata=$(curl -sH "Authorization: token $github_automationbot_token" $urlconfigurationfile)

          # Verify if configuration file was found
          if [[ $configurationdata != *"Not Found"* ]]; then
            echo "  The file was found"
            echo "$configurationdata" > $readFile
          else
            echo "  File not found, returning an empty file"
            touch $readFile
          fi

          echo "  Set the output of the action with the value of the file"
          echo "$configurationdata"
          echo "configuration-data=$(echo $configurationdata)" >> $GITHUB_OUTPUT
        done