##########################################################################
# CICD Pipeline - Debug Github Actions
##########################################################################

name: Debug
on:
  workflow_call:
  
jobs:

  Build:
    name: Debug
    runs-on: ubuntu-latest

    # Assigning permissions to jobs - https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:

      - name: DEBUG variables
        shell: bash
        run: |
          echo " "
          echo "*********************************************"      
          echo "DEBUG variables"
          echo "*********************************************"
          echo " "

          tempvar1=$( echo "${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_APPID }}" | sed 's/./& /g' )
          tempvar2=$( echo "${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_PEM }}" | sed 's/./& /g' )
          echo "  Value for BTFACRM_GITHUB_AUTOMATIONBOT_APPID: $tempvar1"
          echo "  Value for BTFACRM_GITHUB_AUTOMATIONBOT_PEM: $tempvar2"

      #- name: Create a GitHub App installation access token
      #  uses: actions/create-github-app-token@v1
      #  id: app-token
      #  with:
      #    app-id: ${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_APPID }}
      #    private-key: ${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_PEM }}

      - name: Create a GitHub App installation access token
        uses: peter-murray/workflow-application-token-action@v3
        id: app-token
        with:
          application_id: 874519
          application_private_key: ${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_PEM }}

      - name: Verify app token
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Verify App token"
          echo "***********************************************"
          echo " "
          echo " App token: ${{ steps.app-token.outputs.token }}"
          echo "github_automationbot_token=${{ steps.app-token.outputs.token }}" >> $GITHUB_ENV
          exit 1

