##########################################################################
# CICD Pipeline - Debug Github Actions
##########################################################################

name: Debug
on:
  workflow_call:

env:
  CONFIGURATIONS_REPOSITORY: common-configurations
  GLOBAL_CONFIGURATION: _global.yml

jobs:
  Debug:
    name: Debug
    runs-on: ubuntu-latest
    
    # Assigning permissions to jobs - https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    #permissions:
    #  actions: write
    #  checks: write
    #  contents: write
    #  deployments: write
    #  id-token: write
    #  issues: write
    #  discussions: write
    #  packages: write
    #  pages: write
    #  pull-requests: write
    #  repository-projects: write
    #  security-events: write
    #  statuses: write

    steps:

      - name: Create a GitHub App installation access token
        uses: peter-murray/workflow-application-token-action@v3
        id: app-token
        with:
          application_id: ${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_APPID }}
          application_private_key: ${{ secrets.BTFACRM_GITHUB_AUTOMATIONBOT_PEM }}

      - name: Verify app token
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Verify App token"
          echo "***********************************************"
          echo " "
          echo "  App token: ${{ steps.app-token.outputs.token }}"
          echo "github_automationbot_token=${{ steps.app-token.outputs.token }}" >> $GITHUB_ENV
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo " "

      - name: Get secrets from Github
        uses: kanga333/variable-mapper@master
        with:
          key: "master"
          map: |
            {
              "master": {
                  "btfacrm_anypoint_environment_dev_clientid": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_DEV_CLIENTID }}",
                  "btfacrm_anypoint_environment_dev_secret": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_DEV_SECRET }}",
                  "btfacrm_anypoint_environment_prd_clientid": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_PRD_CLIENTID }}",
                  "btfacrm_anypoint_environment_prd_secret": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_PRD_SECRET }}",

                  "btfacrm_apisalesforce_dev_clientsecret": "${{ secrets.BTFACRM_APISALESFORCE_DEV_CLIENTSECRET }}",
                  "btfacrm_apisalesforce_dev_clientid": "${{ secrets.BTFACRM_APISALESFORCE_DEV_CLIENTID }}",
                  "btfacrm_apisalesforce_prd_clientsecret": "${{ secrets.BTFACRM_APISALESFORCE_PRD_CLIENTSECRET }}",
                  "btfacrm_apisalesforce_prd_clientid": "${{ secrets.BTFACRM_APISALESFORCE_PRD_CLIENTID }}",

                  "cicd_connectedapp_clientid": "${{ secrets.BTFACRM_CICD_CONNECTEDAPP_CLIENTID }}",
                  "cicd_connectedapp_secret": "${{ secrets.BTFACRM_CICD_CONNECTEDAPP_SECRET }}",

                  "btfacrm_https_dev_jkspath": "${{ secrets.BTFACRM_HTTPS_DEV_JKSPATH }}",
                  "btfacrm_https_dev_jksalias": "${{ secrets.BTFACRM_HTTPS_DEV_JKSALIAS }}",
                  "btfacrm_https_dev_jkskeypassword": "${{ secrets.BTFACRM_HTTPS_DEV_JKSKEYPASSWORD }}",
                  "btfacrm_https_prd_jkspath": "${{ secrets.BTFACRM_HTTPS_PRD_JKSPATH }}",
                  "btfacrm_https_prd_jksalias": "${{ secrets.BTFACRM_HTTPS_PRD_JKSALIAS }}",
                  "btfacrm_https_prd_jkskeypassword": "${{ secrets.BTFACRM_HTTPS_PRD_JKSKEYPASSWORD }}",

                  "btfacrm_mssql_dev_host": "${{ secrets.BTFACRM_MSSQL_DEV_HOST }}",
                  "btfacrm_mssql_dev_port": "${{ secrets.BTFACRM_MSSQL_DEV_PORT }}",
                  "btfacrm_mssql_dev_user": "${{ secrets.BTFACRM_MSSQL_DEV_USER }}",
                  "btfacrm_mssql_dev_password": "${{ secrets.BTFACRM_MSSQL_DEV_PASSWORD }}",
                  "btfacrm_mssql_dev_database": "${{ secrets.BTFACRM_MSSQL_DEV_DATABASE }}",
                  "btfacrm_mssql_dev_watermark_host": "${{ secrets.BTFACRM_MSSQL_DEV_WATERMARK_HOST }}",
                  "btfacrm_mssql_dev_watermark_port": "${{ secrets.BTFACRM_MSSQL_DEV_WATERMARK_PORT }}",
                  "btfacrm_mssql_dev_watermark_user": "${{ secrets.BTFACRM_MSSQL_DEV_WATERMARK_USER }}",
                  "btfacrm_mssql_dev_watermark_password": "${{ secrets.BTFACRM_MSSQL_DEV_WATERMARK_PASSWORD }}",
                  "btfacrm_mssql_dev_watermark_database": "${{ secrets.BTFACRM_MSSQL_DEV_WATERMARK_DATABASE }}",

                  "btfacrm_mssql_prd_host": "${{ secrets.BTFACRM_MSSQL_PRD_HOST }}",
                  "btfacrm_mssql_prd_port": "${{ secrets.BTFACRM_MSSQL_PRD_PORT }}",
                  "btfacrm_mssql_prd_user": "${{ secrets.BTFACRM_MSSQL_PRD_USER }}",
                  "btfacrm_mssql_prd_password": "${{ secrets.BTFACRM_MSSQL_PRD_PASSWORD }}",
                  "btfacrm_mssql_prd_database": "${{ secrets.BTFACRM_MSSQL_PRD_DATABASE }}",
                  "btfacrm_mssql_prd_watermark_host": "${{ secrets.BTFACRM_MSSQL_PRD_WATERMARK_HOST }}",
                  "btfacrm_mssql_prd_watermark_port": "${{ secrets.BTFACRM_MSSQL_PRD_WATERMARK_PORT }}",
                  "btfacrm_mssql_prd_watermark_user": "${{ secrets.BTFACRM_MSSQL_PRD_WATERMARK_USER }}",
                  "btfacrm_mssql_prd_watermark_password": "${{ secrets.BTFACRM_MSSQL_PRD_WATERMARK_PASSWORD }}",
                  "btfacrm_mssql_prd_watermark_database": "${{ secrets.BTFACRM_MSSQL_PRD_WATERMARK_DATABASE }}",

                  "mulesoft_nexus_ee_user": "${{ secrets.BTFACRM_MULESOFT_NEXUS_EE_USER }}",
                  "mulesoft_nexus_ee_password": "${{ secrets.BTFACRM_MULESOFT_NEXUS_EE_PASSWORD }}",

                  "btfacrm_salesforce_dev_storepassword": "${{ secrets.BTFACRM_SALESFORCE_DEV_STOREPASSWORD }}",
                  "btfacrm_salesforce_dev_principal": "${{ secrets.BTFACRM_SALESFORCE_DEV_PRINCIPAL }}",
                  "btfacrm_salesforce_dev_consumerkey": "${{ secrets.BTFACRM_SALESFORCE_DEV_CONSUMERKEY }}",
                  "btfacrm_salesforce_dev_keystore": "${{ secrets.BTFACRM_SALESFORCE_DEV_KEYSTORE }}",
                  "btfacrm_salesforce_dev_audienceurl": "${{ secrets.BTFACRM_SALESFORCE_DEV_AUDIENCEURL }}",
                  "btfacrm_salesforce_dev_tokenendpoint": "${{ secrets.BTFACRM_SALESFORCE_DEV_TOKENENDPOINT }}",
                  "btfacrm_salesforce_dev_certificatealias": "${{ secrets.BTFACRM_SALESFORCE_DEV_CERTIFICATEALIAS }}",

                  "btfacrm_salesforce_prd_storepassword": "${{ secrets.BTFACRM_SALESFORCE_PRD_STOREPASSWORD }}",
                  "btfacrm_salesforce_prd_principal": "${{ secrets.BTFACRM_SALESFORCE_PRD_PRINCIPAL }}",
                  "btfacrm_salesforce_prd_consumerkey": "${{ secrets.BTFACRM_SALESFORCE_PRD_CONSUMERKEY }}",
                  "btfacrm_salesforce_prd_keystore": "${{ secrets.BTFACRM_SALESFORCE_PRD_KEYSTORE }}",
                  "btfacrm_salesforce_prd_tokenendpoint": "${{ secrets.BTFACRM_SALESFORCE_PRD_TOKENENDPOINT }}",
                  "btfacrm_salesforce_prd_audienceurl": "${{ secrets.BTFACRM_SALESFORCE_PRD_AUDIENCEURL }}",
                  "btfacrm_salesforce_prd_certificatealias": "${{ secrets.BTFACRM_SALESFORCE_PRD_CERTIFICATEALIAS }}"
              }
            }

      - name: Get service configuration
        uses: btfacrm/common-devops/packages/configuration-servicev4@main

      - name: Create badge for deployment
        uses: btfacrm/common-devops/packages/badgev2@main
        with:
          label: '${{ env.deployment_environment }} version'
          status: '${{ env.deployment_version }}'
          color: '535597'
          file: ${{ env.service_name }}-${{ env.deployment_environment }}.svg
          folder: ${{ env.service_name }}