##########################################################################
# CICD Pipeline
##########################################################################

name: Build
on:
  workflow_call:

env:
  DEFAULT_SETTINGS_XML: settings.xml
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  ####################################################################################
  # SECRET MANAGEMENT - TEST TO DO THE SECRET MANAGEMENT ENTIRELY WITH GITHUB SECRETS
  ####################################################################################

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Test step
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Print a secret"
          echo "***********************************************"
          echo " "

          echo "secret: ${{ secrets.SALESFORCE_DEV_KEYSTORE }}"
          salesforce_dev_keystore="${{ secrets.SALESFORCE_DEV_KEYSTORE }}"
          echo "salesforce_dev_keystore = $salesforce_dev_keystore"
          
          tempvar=$( echo "${{ secrets.GH_ADMINTASKS_ACCESSTOKEN }}" | sed 's/./& /g' )
          echo "GH_ADMINTASKS_ACCESSTOKEN: $tempvar"
          
          # Set environment variables
          echo "github_admintasks_accesstoken=${{ secrets.GH_ADMINTASKS_ACCESSTOKEN }}" >> $GITHUB_ENV

          # Show environment variables
          echo "github_admintasks_accesstoken: $github_admintasks_accesstoken"

      - name: Get configuration file
        env:
          SECRET_MAP_FILE: _secrets-github.json
        shell: bash
        run: |
          echo " "
          echo "*********************************************"
          echo "Get global configuration"
          echo "*********************************************"

          echo "github_admintasks_accesstoken: $github_admintasks_accesstoken"
          echo "github.token: ${{ github.token }}"

          # Get the configuration file from the github repository
          urlconfigurationfile="https://raw.githubusercontent.com/${{ github.repository_owner }}/$CONFIGURATIONS_REPOSITORY/main/$SECRET_MAP_FILE"
          echo "Getting the secrets mapping file: $urlconfigurationfile"
          # initialsecretconfiguration=$(curl -sH "Authorization: token $github_admintasks_accesstoken" $urlconfigurationfile)
          initialsecretconfiguration=$(curl -sH "Authorization: token ${{ github.token }}" $urlconfigurationfile)

          # Verify if configuration file was found
          if [[ $configurationdata != *"Not Found"* ]]; then
            echo "A configuration file for the service was found"
            
            # Write the configuration file in the filesystem
            echo "$initialsecretconfiguration" > global.yml
          else
            echo "No configuration file found, returning an empty file"
            touch global.yml
          fi

          echo "$initialsecretconfiguration"

      - name: Echo environment
        shell: bash
        run: |
          cat global.yml