##########################################################################
# CICD Pipeline
##########################################################################

name: Build
on:
  workflow_call:
    inputs:
      keyvault-key:
        required: true
        description: Access key to KeyVault
        type: string
    secrets:
      azure-credentials:
        required: true
        description: Azure Credentials for login
env:
  DEFAULT_SETTINGS_XML: settings.xml
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  ##########################################################################
  # BUILD MULESOFT SERVICE
  ##########################################################################

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get secrets from Github
        uses: kanga333/variable-mapper@master
        with:
          key: "master"
          # map: "${{steps.get-secrets-github.outputs.configuration-data}}"
          map: |
            {
              "master": {
                  "btfacrm_anypoint_environment_dev_clientid": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_DEV_CLIENTID }}",
                  "btfacrm_anypoint_environment_dev_secret": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_DEV_SECRET }}",
                  "btfacrm_anypoint_environment_prd_clientid": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_PRD_CLIENTID }}",
                  "btfacrm_anypoint_environment_prd_secret": "${{ secrets.BTFACRM_ANYPOINT_ENVIRONMENT_PRD_SECRET }}",

                  "btfacrm_apisalesforce_dev_clientsecret": "${{ secrets.BTFACRM_APISALESFORCE_DEV_CLIENTSECRET }}",
                  "btfacrm_apisalesforce_dev_clientid": "${{ secrets.BTFACRM_APISALESFORCE_PRD_CLIENTID }}",
                  "btfacrm_apisalesforce_prd_clientid": "${{ secrets.BTFACRM_HTTPS_DEV_JKSKEYPASSWORD }}",
                  "btfacrm_apisalesforce_prd_clientsecret": "${{ secrets.BTFACRM_APISALESFORCE_PRD_CLIENTSECRET }}",

                  "cicd_connectedapp_clientid": "${{ secrets.BTFACRM_CICD_CONNECTEDAPP_CLIENTID }}",
                  "cicd_connectedapp_secret": "${{ secrets.BTFACRM_CICD_CONNECTEDAPP_SECRET }}",

                  "github_admintasks_accesstoken": "${{ secrets.BTFACRM_GITHUB_ADMINTASKS_ACCESSTOKEN }}",

                  "btfacrm_https_dev_jkspath": "${{ secrets.BTFACRM_HTTPS_DEV_JKSPATH }}",
                  "btfacrm_https_dev_jksalias": "${{ secrets.BTFACRM_HTTPS_DEV_JKSALIAS }}",
                  "btfacrm_https_dev_jkskeypassword": "${{ secrets.BTFACRM_HTTPS_DEV_JKSKEYPASSWORD }}",
                  "btfacrm_https_prd_jkspath": "${{ secrets.BTFACRM_HTTPS_PRD_JKSPATH }}",
                  "btfacrm_https_prd_jksalias": "${{ secrets.BTFACRM_HTTPS_PRD_JKSALIAS }}",
                  "btfacrm_https_prd_jkskeypassword": "${{ secrets.BTFACRM_HTTPS_PRD_JKSKEYPASSWORD }}",

                  "btfacrm_mssql_dev_host": "${{ secrets.BTFACRM_MSSQL_DEV_HOST }}",
                  "btfacrm_mssql_dev_port": "${{ secrets.BTFACRM_MSSQL_DEV_PORT }}",
                  "btfacrm_mssql_dev_user": "${{ secrets.BTFACRM_MSSQL_DEV_USER }}",
                  "btfacrm_mssql_dev_password": "${{ secrets.BTFACRM_MSSQL_DEV_PASSWORD }}",
                  "btfacrm_mssql_dev_database": "${{ secrets.BTFACRM_MSSQL_DEV_DATABASE }}",

                  "btfacrm_mssql_prd_host": "${{ secrets.BTFACRM_MSSQL_PRD_HOST }}",
                  "btfacrm_mssql_prd_port": "${{ secrets.BTFACRM_MSSQL_PRD_PORT }}",
                  "btfacrm_mssql_prd_user": "${{ secrets.BTFACRM_MSSQL_PRD_USER }}",
                  "btfacrm_mssql_prd_password": "${{ secrets.BTFACRM_MSSQL_PRD_PASSWORD }}",
                  "btfacrm_mssql_prd_database": "${{ secrets.BTFACRM_MSSQL_PRD_DATABASE }}",

                  "mulesoft_nexus_ee_user": "${{ secrets.BTFACRM_MULESOFT_NEXUS_EE_USER }}",
                  "mulesoft_nexus_ee_password": "${{ secrets.BTFACRM_MULESOFT_NEXUS_EE_PASSWORD }}",

                  "btfacrm_salesforce_dev_storepassword": "${{ secrets.BTFACRM_SALESFORCE_DEV_STOREPASSWORD }}",
                  "btfacrm_salesforce_dev_principal": "${{ secrets.BTFACRM_SALESFORCE_DEV_PRINCIPAL }}",
                  "btfacrm_salesforce_dev_consumerkey": "${{ secrets.BTFACRM_SALESFORCE_DEV_CONSUMERKEY }}",
                  "btfacrm_salesforce_dev_keystore": "${{ secrets.BTFACRM_SALESFORCE_DEV_KEYSTORE }}",
                  "btfacrm_salesforce_dev_audienceurl": "${{ secrets.BTFACRM_SALESFORCE_DEV_AUDIENCEURL }}",
                  "btfacrm_salesforce_dev_tokenendpoint": "${{ secrets.BTFACRM_SALESFORCE_DEV_TOKENENDPOINT }}",
                  "btfacrm_salesforce_dev_certificatealias": "${{ secrets.BTFACRM_SALESFORCE_DEV_CERTIFICATEALIAS }}",

                  "btfacrm_salesforce_prd_storepassword": "${{ secrets.BTFACRM_SALESFORCE_PRD_STOREPASSWORD }}",
                  "btfacrm_salesforce_prd_principal": "${{ secrets.BTFACRM_SALESFORCE_PRD_PRINCIPAL }}",
                  "btfacrm_salesforce_prd_consumerkey": "${{ secrets.BTFACRM_SALESFORCE_PRD_CONSUMERKEY }}",
                  "btfacrm_salesforce_prd_keystore": "${{ secrets.BTFACRM_SALESFORCE_PRD_KEYSTORE }}",
                  "btfacrm_salesforce_prd_tokenendpoint": "${{ secrets.BTFACRM_SALESFORCE_PRD_TOKENENDPOINT }}",
                  "btfacrm_salesforce_prd_audienceurl": "${{ secrets.BTFACRM_SALESFORCE_PRD_AUDIENCEURL }}",
                  "btfacrm_salesforce_prd_certificatealias": "${{ secrets.BTFACRM_SALESFORCE_PRD_CERTIFICATEALIAS }}"
              }
            }

      - name: Get global configuration
        uses: btfacrm/common-devops/packages/configuration-servicev2@main
        with:
          environment: build

      - id: issue-create
        name: Create a deployment issue
        if: "env.configuration_environments != '' && !contains(env.service_version, 'snapshot')"
        env:
          GITHUB_TOKEN: ${{ env.github_admintasks_accesstoken }}
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Create Deployment Issue "
          echo "***********************************************"
          echo " "
          echo "  Create issue for deployment in the first environment"

          # Environment list to an array
          environmentarray=($configuration_environments)
          
          echo "  Environment to deploy the application: ${environmentarray[0]}
          #gh -R "${{ github.repository }}" issue create \
          #    -t "Deployment dev ${{ env.service_name }} ${{ env.service_version }}" \
          #    -a "${{ env.github_deployeruser }}" \
          #    -b "The build job triggered this action. An analysis task will be responsible for checking if the service is deployable." \
          #    -l "forward,dev"