##########################################################################
# CICD Pipeline
##########################################################################

name: Build
on:
  workflow_call:

env:
  DEFAULT_SETTINGS_XML: settings.xml
  CONFIGURATIONS_REPOSITORY: common-configurations
  SECRETS_GITHUB_FILE: _secrets-github.json
jobs:

  ####################################################################################
  # SECRET MANAGEMENT - TEST TO DO THE SECRET MANAGEMENT ENTIRELY WITH GITHUB SECRETS
  ####################################################################################

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      repository-projects: read

    steps:
      - name: Get the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set github token variable
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Print a secret"
          echo "***********************************************"
          echo " "
          tempvar=$( echo "${{ secrets.GH_ADMINTASKS_ACCESSTOKEN }}" | sed 's/./& /g' )
          echo "GH_ADMINTASKS_ACCESSTOKEN: $tempvar"
          # echo "github_admintasks_accesstoken=${{ secrets.GH_ADMINTASKS_ACCESSTOKEN }}" >> $GITHUB_ENV
          echo "github_admintasks_accesstoken=${{ github.token }}" >> $GITHUB_ENV

      - name: Get secrets file
        id: get-secrets-github
        uses: btfacrm/common-devops/packages/get-file@main
        with:
          file: _secrets-github.json

      - uses: kanga333/variable-mapper@master
        with:
          key: "master"
          # map: "${{steps.get-secrets-github.outputs.configuration-data}}"
          map: |
            {
              "master": {
                  "jks_dev_keypassword": "${{ secrets.JKS_DEV_KEYPASSWORD }}",
                  "jks_dev_alias": "${{ secrets.JKS_DEV_ALIAS }}",
                  "jks_dev_keypassword": "${{ secrets.JKS_DEV_KEYPASSWORD }}",
                  "salesforce_dev_keystore": "${{ secrets.SALESFORCE_DEV_KEYSTORE }}",
                  "salesforce_dev_storepassword": "${{ secrets.SALESFORCE_DEV_STOREPASSWORD }}",
                  "salesforce_dev_certificatealias": "${{ secrets.SALESFORCE_DEV_CERTIFICATEALIAS }}"
              }
            }

      - name: Get configurations
        id: get-configurations
        uses: btfacrm/common-devops/packages/get-file@main
        with:
          file: _global.yml
          
      - name: Import variables from global.yml
        uses: zlatko-ms/envarfiles@main
        with:
          paths: _global.yml

      - name: Print environment variables
        shell: bash
        run: |
          echo "salesforce_dev_keystore: $salesforce_dev_keystore"
          echo $salesforce_dev_keystore | sed 's/./& /g'
