##########################################################################
# CICD Pipeline
##########################################################################

name: Build
on:
  workflow_call:

env:
  DEFAULT_SETTINGS_XML: settings.xml
  CONFIGURATIONS_REPOSITORY: common-configurations
  
jobs:

  ####################################################################################
  # SECRET MANAGEMENT - TEST TO DO THE SECRET MANAGEMENT ENTIRELY WITH GITHUB SECRETS
  ####################################################################################

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Test step
        shell: bash
        run: |
          echo " "
          echo "***********************************************"
          echo "Print a secret"
          echo "***********************************************"
          echo " "

          echo "secret: ${{ secrets.SALESFORCE_DEV_KEYSTORE }}"
          salesforce_dev_keystore="${{ secrets.SALESFORCE_DEV_KEYSTORE }}"
          echo "salesforce_dev_keystore = $salesforce_dev_keystore"
          
          tempvar=$( echo "${{ secrets.GH_ADMINTASKS_ACCESSTOKEN }}" | sed 's/./& /g' )
          echo "GH_ADMINTASKS_ACCESSTOKEN: $tempvar"
          
          # Set environment variables
          echo "github_admintasks_accesstoken=${{ secrets.GH_ADMINTASKS_ACCESSTOKEN }}" >> $GITHUB_ENV

          # Show environment variables
          echo "github_admintasks_accesstoken: $github_admintasks_accesstoken"

      - name: Get secrets file
        id: get-secrets-file
        uses: btfacrm/common-devops/packages/get-file@main
        with:
          file: _secrets-github.json

      - name: Echo environment
        shell: bash
        run: |
          cat _secrets-github.json